### ISSUE TITLE
Structures Float on Gravel Beaches

### ISSUE THREAD

**Issue by DarianLStephens** [b3spectacled/classic-beaches#1]
The way gravel beaches seem to work is by removing the top layer, or having it generate as air or something.
Unfortunately, villages and other structures still generate on top of this non-existent surface layer, and so they float slightly off the ground, with doors unreachable by villagers if it so happens to generate on a gravel beach.

Is there anything you can do about this, or is it just an unfortunate side-effect of the way they're done?

**Comment by b3spectacled** [comment]
Yep, you're correct, it's unfortunately a side effect of how gravel beaches generate.  The topmost layer of a gravel beach is replaced with air (which is why they're always two blocks deep).

EDIT: I will still see if I can figure out a solution, so if you can provide a seed and coords where this happens, I would appreciate it.

**Comment by DarianLStephens** [comment]
I finally found something after a while of searching. There's a stable on a patch of gravel here:
Seed: [-1516676597421523484]
`/tp -82853.97 82.57 -75698.72 -234.68 32.24`
(The full command was `/execute in minecraft:overworld run tp @s -82853.97 82.57 -75698.72 -234.68 32.24`, if it's of any use)
I unfortunately couldn't use any of my previous seeds seeing as I used biome and other generation mods in them, and you can see by the coordinates just how far I traveled to find this one.

A picture of the stable for reference:
![2021-03-15_23 35 43](https://user-images.githubusercontent.com/15375876/111154311-35b62080-85e7-11eb-8782-3c6d88173889.png)
I also ran in to _many_ almost-hits.
This one felt particularly mocking, though:
![2021-03-15_23 03 37](https://user-images.githubusercontent.com/15375876/111154397-49fa1d80-85e7-11eb-82c3-49be5c8ada0a.png)

**Comment by b3spectacled** [comment]
Apologies for the delay, this was a tricky issue and I got up caught up in other things.  Just fixed with c585fd7.  Unfortunately, the best solution I could think of was to simply give an option to generate gravel beaches at the same height as sand beaches.
